/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serieseval.forms;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.SpinnerUI;
import serieseval.Mainl;
import serieseval.ProcessArff;
import serieseval.Seguridad;
import serieseval.controller.ArffController;
import serieseval.model.User;
import weka.classifiers.trees.DecisionStump;

/**
 *
 * @author Laura
 */
public class InicioSesionForm extends javax.swing.JPanel {

    /**
     * Creates new form CargarAffForm
     */
    public InicioSesionForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testOptionsBtnGroup = new javax.swing.ButtonGroup();
        seriesevalPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("seriesevalPU").createEntityManager();
        userQuery = java.beans.Beans.isDesignTime() ? null : seriesevalPUEntityManager.createQuery("SELECT a FROM User a");
        userList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : userQuery.getResultList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuarioJText = new javax.swing.JTextField();
        iniciarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contraseñaJText = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel5.setText("Usuario");

        jLabel6.setText("Contraseña");

        iniciarBtn.setText("Iniciar");
        iniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Escriba sus credenciales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iniciarBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioJText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addComponent(contraseñaJText))))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usuarioJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(contraseñaJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(iniciarBtn)
                .addContainerGap(431, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        // TODO add your handling code here:
        User usuarioInicio = null;
        for (User user : userList) {
            if ((user.getUsername() == null ? usuarioJText.getText() == null : user.getUsername().equals(usuarioJText.getText())) && (user.getPassword() == null ? contraseñaJText.getText() == null : user.getPassword().equals(contraseñaJText.getText()))) {
                usuarioInicio = user;
                break;
            }
        }
        if (usuarioInicio != null) {
            Seguridad.SetUsuario(usuarioInicio);

            Principal principal = (Principal) this.getParent().getParent().getParent().getParent();
            principal.Menu(true);
            
            principal.getContentPane().removeAll();            
            principal.getContentPane().setSize(300, 300);
            principal.revalidate();
            principal.repaint();
        }
        else{            
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta.");
        }
    }//GEN-LAST:event_iniciarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaJText;
    private javax.swing.JButton iniciarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.persistence.EntityManager seriesevalPUEntityManager;
    private javax.swing.ButtonGroup testOptionsBtnGroup;
    private java.util.List<serieseval.model.User> userList;
    private javax.persistence.Query userQuery;
    private javax.swing.JTextField usuarioJText;
    // End of variables declaration//GEN-END:variables
}
