/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serieseval.forms;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import serieseval.ProcessArff;
import serieseval.Seguridad;
import serieseval.forms.Usuario.UsuariosForm;
import serieseval.forms.algorithmGroup.GroupForm;
import serieseval.forms.algorithms.AlgorithmForm;
import serieseval.forms.experimento.ExperimentForm;
import serieseval.forms.testOption.TestOptionForm;
import weka.classifiers.trees.DecisionStump;

/**
 *
 * @author Laura
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        if (Seguridad.UsuarioActual() == null) {
            RolAdministrador(false);
            InicioSesionForm u = new InicioSesionForm();
            u.setVisible(true);
            this.getContentPane().removeAll();
            this.getContentPane().setLayout(new BorderLayout());
            this.getContentPane().add(u);
            this.getContentPane().setSize(1024, 768);
            this.revalidate();
            this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        menu = new javax.swing.JMenuBar();
        resultadosMenu = new javax.swing.JMenu();
        mostrarResuladosMenu = new javax.swing.JMenuItem();
        procesarMenu = new javax.swing.JMenu();
        experimentMenu = new javax.swing.JMenuItem();
        configuracionMenu = new javax.swing.JMenu();
        clasificadoresMenu = new javax.swing.JMenu();
        grupoAlgoritmoMenu = new javax.swing.JMenuItem();
        algoritmosMenu = new javax.swing.JMenuItem();
        testOptionMenu = new javax.swing.JMenuItem();
        usuarioMenu = new javax.swing.JMenuItem();
        cerrarSesionMenu = new javax.swing.JMenu();
        cerrarSesionMenuItem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 600));

        resultadosMenu.setText("Resultados");

        mostrarResuladosMenu.setText("Mostrar Resultados");
        mostrarResuladosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarResuladosMenuActionPerformed(evt);
            }
        });
        resultadosMenu.add(mostrarResuladosMenu);

        menu.add(resultadosMenu);

        procesarMenu.setText("Procesar");

        experimentMenu.setText("Experimentos");
        experimentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experimentMenuActionPerformed(evt);
            }
        });
        procesarMenu.add(experimentMenu);

        menu.add(procesarMenu);

        configuracionMenu.setText("Configuracion");
        configuracionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configuracionMenuMouseClicked(evt);
            }
        });

        clasificadoresMenu.setText("Clasificadores");

        grupoAlgoritmoMenu.setText("Grupos de algoritmos");
        grupoAlgoritmoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoAlgoritmoMenuActionPerformed(evt);
            }
        });
        clasificadoresMenu.add(grupoAlgoritmoMenu);

        algoritmosMenu.setText("Algoritmos");
        algoritmosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoritmosMenuActionPerformed(evt);
            }
        });
        clasificadoresMenu.add(algoritmosMenu);

        testOptionMenu.setText("Opciones de prueba");
        testOptionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testOptionMenuActionPerformed(evt);
            }
        });
        clasificadoresMenu.add(testOptionMenu);

        configuracionMenu.add(clasificadoresMenu);

        usuarioMenu.setText("Usuarios");
        usuarioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMenuMouseClicked(evt);
            }
        });
        usuarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuActionPerformed(evt);
            }
        });
        configuracionMenu.add(usuarioMenu);

        menu.add(configuracionMenu);

        cerrarSesionMenu.setText("Usuario");

        cerrarSesionMenuItem.setText("Cerrar Sesión");
        cerrarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionMenuItemActionPerformed(evt);
            }
        });
        cerrarSesionMenu.add(cerrarSesionMenuItem);

        menu.add(cerrarSesionMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMenuMouseClicked
        // TODO add your handling code here:       
    }//GEN-LAST:event_usuarioMenuMouseClicked

    private void configuracionMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuracionMenuMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_configuracionMenuMouseClicked

    private void usuarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuActionPerformed
        // TODO add your handling code here:
        UsuariosForm u = new UsuariosForm();
        this.setTitle("Usuarios");
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();

        //JOptionPane.showMessageDialog(null, "No hay nada que mostrar.");
    }//GEN-LAST:event_usuarioMenuActionPerformed

    public void Menu(Boolean visible) {
        String role = Seguridad.UsuarioActual().getIdRole().getRoleName();
        switch (role) {
            case "Administrador": {
                RolAdministrador(visible);
                break;
            }
            case "Experto": {
                RolExperto(visible);
                break;
            }
            case "Usuario": {
                RolUsuario(visible);
                break;
            }
        }

    }

    private void RolAdministrador(Boolean visible) {
        resultadosMenu.setEnabled(visible);
        procesarMenu.setEnabled(visible);
        configuracionMenu.setEnabled(visible);
        cerrarSesionMenu.setEnabled(visible);
    }

    private void RolExperto(Boolean visible) {
        resultadosMenu.setEnabled(visible);
        procesarMenu.setEnabled(visible);
        cerrarSesionMenu.setEnabled(visible);

    }

    private void RolUsuario(Boolean visible) {
        resultadosMenu.setEnabled(visible);
        cerrarSesionMenu.setEnabled(visible);
    }

    private void grupoAlgoritmoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoAlgoritmoMenuActionPerformed
        // TODO add your handling code here:
        GroupForm u = new GroupForm();
        this.setTitle("Grupo de algoritmos");
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_grupoAlgoritmoMenuActionPerformed

    private void algoritmosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoritmosMenuActionPerformed
        // TODO add your handling code here:
        AlgorithmForm u = new AlgorithmForm();
        this.setTitle("Algoritmo");
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_algoritmosMenuActionPerformed

    private void testOptionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testOptionMenuActionPerformed
        // TODO add your handling code here:
        TestOptionForm u = new TestOptionForm();
        this.setTitle("Opciones de pruebas");
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_testOptionMenuActionPerformed

    private void experimentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experimentMenuActionPerformed
        // TODO add your handling code here:
        ExperimentForm u = new ExperimentForm();
        this.setTitle("Experimentos");
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_experimentMenuActionPerformed

    private void cerrarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionMenuItemActionPerformed
        // TODO add your handling code here:
        Seguridad.SetUsuario(null);
        RolAdministrador(false);
        InicioSesionForm u = new InicioSesionForm();
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();

    }//GEN-LAST:event_cerrarSesionMenuItemActionPerformed

    private void mostrarResuladosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarResuladosMenuActionPerformed
        // TODO add your handling code here:
        serieseval.forms.Resultados.ExperimentForm u = new serieseval.forms.Resultados.ExperimentForm();
        this.setTitle("Resultados");
        u.setVisible(true);
        this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(u);
        this.getContentPane().setSize(1024, 768);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_mostrarResuladosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem algoritmosMenu;
    private javax.swing.JMenu cerrarSesionMenu;
    private javax.swing.JMenuItem cerrarSesionMenuItem;
    private javax.swing.JMenu clasificadoresMenu;
    public javax.swing.JMenu configuracionMenu;
    private javax.swing.JMenuItem experimentMenu;
    private javax.swing.JMenuItem grupoAlgoritmoMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem mostrarResuladosMenu;
    public javax.swing.JMenu procesarMenu;
    public javax.swing.JMenu resultadosMenu;
    private javax.swing.JMenuItem testOptionMenu;
    private javax.swing.JMenuItem usuarioMenu;
    // End of variables declaration//GEN-END:variables
}
