/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serieseval.forms.Resultados;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import serieseval.Graficos;
import serieseval.ProcessArff;
import serieseval.Seguridad;
import serieseval.ValorCalculado;
import serieseval.controller.AlgorithmController;
import serieseval.controller.ArffController;
import serieseval.controller.ExperimentController;
import serieseval.controller.UserController;
import serieseval.forms.algorithms.*;
import serieseval.model.Algorithm;
import serieseval.model.Datasource;
import serieseval.model.Dmresult;
import serieseval.model.Experimentgroup;
import serieseval.model.User;
import weka.core.converters.ConverterUtils;

/**
 *
 * @author Laura
 */
public class AnalisisGraphForm extends javax.swing.JPanel {

    Dmresult result;

    /**
     * Creates new form Usuarios
     */
    public AnalisisGraphForm(Dmresult result) {
        initComponents();
        this.result = result;
        mesesSpiner.setValue(6);
        ShowGrafico(6);
    }

    private void ShowGrafico(Integer cantMeses) {

        ArffController c = new ArffController();
        Double[] data = c.GetDataParaGrafico(result, cantMeses);
        if (data == null) {
            JOptionPane.showMessageDialog(null, "La cantidad de meses seleccionada es mayor que la cantidad de meses en el fichero.");
        } else {
            Graficos g = new Graficos();
            graficoLabel.setIcon(new ImageIcon(g.AnalisisGrafico("Predicción", data)));
            this.revalidate();
            this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seriesevalPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("seriesevalPU").createEntityManager();
        algorithmQuery = java.beans.Beans.isDesignTime() ? null : seriesevalPUEntityManager.createQuery("SELECT a FROM Algorithm a");
        algorithmList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : algorithmQuery.getResultList();
        experimentgroupQuery = java.beans.Beans.isDesignTime() ? null : seriesevalPUEntityManager.createQuery("SELECT e FROM Experimentgroup e");
        experimentgroupList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : experimentgroupQuery.getResultList();
        atrasBtn = new javax.swing.JButton();
        graficoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mesesSpiner = new javax.swing.JSpinner();
        refrescarBtn = new javax.swing.JButton();

        atrasBtn.setText("Atrás");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Meses a mostrar:");

        refrescarBtn.setText("Refrescar");
        refrescarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(graficoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(atrasBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mesesSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refrescarBtn)))
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mesesSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarBtn))
                .addGap(7, 7, 7)
                .addComponent(graficoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atrasBtn)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        if (Seguridad.UsuarioActual().getIdRole().getRoleName().equals("Usuario")) {
            ExperimentForm u = new ExperimentForm();
            u.setVisible(true);
            Container c = this.getParent();
            c.removeAll();
            c.setLayout(new BorderLayout());
            c.add(u);
            c.setSize(300, 300);
            c.revalidate();
            c.repaint();

        } else {
            ResultsForm u = new ResultsForm(result.getDatasource().getIdexperimentgroup());
            u.setVisible(true);
            Container c = this.getParent();
            c.removeAll();
            c.setLayout(new BorderLayout());
            c.add(u);
            c.setSize(300, 300);
            c.revalidate();
            c.repaint();
        }


    }//GEN-LAST:event_atrasBtnActionPerformed

    private void refrescarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarBtnActionPerformed
        // TODO add your handling code here:
        ShowGrafico((Integer) mesesSpiner.getValue());
    }//GEN-LAST:event_refrescarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<serieseval.model.Algorithm> algorithmList;
    private javax.persistence.Query algorithmQuery;
    private javax.swing.JButton atrasBtn;
    private java.util.List<serieseval.model.Experimentgroup> experimentgroupList;
    private javax.persistence.Query experimentgroupQuery;
    private javax.swing.JLabel graficoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner mesesSpiner;
    private javax.swing.JButton refrescarBtn;
    private javax.persistence.EntityManager seriesevalPUEntityManager;
    // End of variables declaration//GEN-END:variables

    public void persist(Object object) {
        seriesevalPUEntityManager.getTransaction().begin();
        try {
            seriesevalPUEntityManager.persist(object);
            seriesevalPUEntityManager.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
            seriesevalPUEntityManager.getTransaction().rollback();
        } finally {
            seriesevalPUEntityManager.close();
        }
    }
}
