/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serieseval.forms.experimento;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import serieseval.controller.AlgorithmController;
import serieseval.controller.ArffController;
import serieseval.controller.ExperimentController;
import serieseval.controller.UserController;
import serieseval.forms.algorithms.*;
import serieseval.model.Algorithm;
import serieseval.model.Datasource;
import serieseval.model.Dmgroup;
import serieseval.model.Experimentgroup;
import serieseval.model.Role;
import serieseval.model.User;

/**
 *
 * @author Laura
 */
public class EditarExperiment extends javax.swing.JPanel {

    public Experimentgroup experiment;

    /**
     * Creates new form CreateUser
     */
    public EditarExperiment(Experimentgroup experiment) {
        this.experiment = experiment;
        initComponents();

        datasourceList.setListData(experiment.getDatasourceCollection().toArray());
        usernameTbox.setText(experiment.getDescription());
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        fechaTBox.setText(format.format(experiment.getFecha()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seriesevalPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("seriesevalPU").createEntityManager();
        dmgroupQuery = java.beans.Beans.isDesignTime() ? null : seriesevalPUEntityManager.createQuery("SELECT d FROM Dmgroup d");
        dmgroupList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dmgroupQuery.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameTbox = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        pruebasBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datasourceList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        fechaTBox = new javax.swing.JFormattedTextField();

        jLabel1.setText("Descripción");

        jLabel6.setText("Fecha");

        saveBtn.setText("Guardar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        pruebasBtn.setText("Ejecutar pruebas");
        pruebasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebasBtnActionPerformed(evt);
            }
        });

        datasourceList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(datasourceList);

        jLabel2.setText("Datasources:");

        fechaTBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fechaTBox.setToolTipText("");
        fechaTBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTbox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaTBox)))
                    .addComponent(pruebasBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(saveBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cancelarBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fechaTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pruebasBtn)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarBtn)
                    .addComponent(saveBtn))
                .addGap(120, 120, 120))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        ExperimentController uc = new ExperimentController();

        if (fechaTBox.isEditValid() && fechaTBox.getValue() != null) {
            experiment.setDescription(usernameTbox.getText());
            experiment.setFecha((Date)fechaTBox.getValue());
            uc.Editar(experiment);
            ExperimentForm u = new ExperimentForm();
            u.setVisible(true);
            Container c = this.getParent();
            c.removeAll();
            c.add(u);
            c.revalidate();
            c.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "Fecha incorrecta.");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        ExperimentForm u = new ExperimentForm();
        u.setVisible(true);

        Container c = this.getParent();
        c.removeAll();
        c.setLayout(new BorderLayout());
        c.add(u);
        c.setSize(1024, 768);
        c.revalidate();
        c.repaint();

    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void pruebasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebasBtnActionPerformed
        // TODO add your handling code here:        
        EjecutarPruebasForm u = new EjecutarPruebasForm(experiment);
        u.setVisible(true);

        Container c = this.getParent();
        c.removeAll();
        c.setLayout(new BorderLayout());
        c.add(u);
        c.setSize(1024, 768);
        c.revalidate();
        c.repaint();

    }//GEN-LAST:event_pruebasBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JList datasourceList;
    private java.util.List<serieseval.model.Dmgroup> dmgroupList;
    private javax.persistence.Query dmgroupQuery;
    private javax.swing.JFormattedTextField fechaTBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pruebasBtn;
    private javax.swing.JButton saveBtn;
    private javax.persistence.EntityManager seriesevalPUEntityManager;
    private javax.swing.JTextField usernameTbox;
    // End of variables declaration//GEN-END:variables
}
