/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serieseval.forms.algorithms;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import serieseval.controller.AlgorithmController;
import serieseval.controller.UserController;
import serieseval.model.Algorithm;
import serieseval.model.Dmgroup;
import serieseval.model.Role;
import serieseval.model.User;

/**
 *
 * @author Laura
 */
public class EditarAlgorithm extends javax.swing.JPanel {

    public Algorithm algoritmo;

    /**
     * Creates new form CreateUser
     */
    public EditarAlgorithm(Algorithm algoritmo) {
        this.algoritmo = algoritmo;
        initComponents();

        nombreTbox.setText(algoritmo.getName());
        rolComboBox.setSelectedItem(algoritmo.getIdgroup());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        seriesevalPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("seriesevalPU").createEntityManager();
        dmgroupQuery = java.beans.Beans.isDesignTime() ? null : seriesevalPUEntityManager.createQuery("SELECT d FROM Dmgroup d");
        dmgroupList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dmgroupQuery.getResultList();
        jLabel1 = new javax.swing.JLabel();
        rolComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        nombreTbox = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, dmgroupList, rolComboBox);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel6.setText("Grupo");

        saveBtn.setText("Guardar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTbox)
                            .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreTbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        Boolean valido = true;
        String nombre = nombreTbox.getText();
        String[] nombreSplit;
        nombreSplit = nombre.split("[.]");

        if (nombreSplit.length != 4) {
            valido = false;
        }
        if (valido && !"weka".equals(nombreSplit[0])) {
            valido = false;
        }
        if (valido && !"classifiers".equals(nombreSplit[1])) {
            valido = false;
        }
        Dmgroup grupo = (Dmgroup) rolComboBox.getSelectedItem();
        if (valido && (nombreSplit[2] == null ? grupo.getName().toLowerCase() != null : !nombreSplit[2].equals(grupo.getName().toLowerCase()))) {
            valido = false;
        }

        if (valido) {
            AlgorithmController uc = new AlgorithmController();

            algoritmo.setName(nombreTbox.getText());
            algoritmo.setIdgroup((Dmgroup) rolComboBox.getSelectedItem());

            uc.Editar(algoritmo);
            AlgorithmForm u = new AlgorithmForm();
            u.setVisible(true);
            Container c = this.getParent();
            c.removeAll();
            c.add(u);
            c.revalidate();
            c.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "Nombre no válido.");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        AlgorithmForm u = new AlgorithmForm();
        u.setVisible(true);

        Container c = this.getParent();
        c.removeAll();
        c.setLayout(new BorderLayout());
        c.add(u);
        c.setSize(300, 300);
        c.revalidate();
        c.repaint();

    }//GEN-LAST:event_cancelarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private java.util.List<serieseval.model.Dmgroup> dmgroupList;
    private javax.persistence.Query dmgroupQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreTbox;
    private javax.swing.JComboBox rolComboBox;
    private javax.swing.JButton saveBtn;
    private javax.persistence.EntityManager seriesevalPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
